const schools = [
    {
        schoolName: 'Louisiana State University',
        athleticsURL: 'https://lsusports.net/',
        location: 'Baton Rouge, LA',
        logo: 'https://storage.googleapis.com/lsusports-com/2021/06/3c6e097b-logo.svg',
        primaryBackground: '',
        primaryText: '',
        safeTextWhite: '',
        safeTextBlack: '',
    },
    {
        schoolName: 'University of Miami (Florida)',
        athleticsURL: 'https://miamihurricanes.com/',
        location: 'Coral Gables, FL',
        logo: 'https://storage.googleapis.com/hurricanesports-com/2020/06/5260964f-miami_hurricanes_logo-1.png',
        primaryBackground: '',
        primaryText: '',
        safeTextWhite: '',
        safeTextBlack: '',
    },
    {
        schoolName: 'University of Notre Dame',
        athleticsURL: 'https://und.com/',
        location: 'Notre Dame, IN',
        logo: 'https://und.com/imgproxy/WS8x7ZNyXnYNwWTguqQyy3AzNB8dGcvOPvNDpTsbpjQ/fit/500/500/ce/0/aHR0cHM6Ly91bmQuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE5LzA5L05EX01vbm9ncmFtXzIwMTVfT25lX0NvbG9yX2dvbGQucG5n.png',
        primaryBackground: '',
        primaryText: '',
        safeTextWhite: '',
        safeTextBlack: '',
    },
    {
        schoolName: 'University of Arkansas, Fayetteville',
        athleticsURL: 'https://arkansasrazorbacks.com/',
        location: 'Fayetteville, AR',
        logo: 'https://arkansasrazorbacks.com/wp-content/uploads/2018/10/hog_white.png',
        primaryBackground: '',
        primaryText: '',
        safeTextWhite: '',
        safeTextBlack: '',
    },
    {
        schoolName: 'University of Iowa',
        athleticsURL: 'https://hawkeyesports.com/',
        location: 'Iowa City, IA',
        logo: 'https://storage.googleapis.com/hawkeyesports-com/2021/02/cf540990-logo.png',
        primaryBackground: '',
        primaryText: '',
        safeTextWhite: '',
        safeTextBlack: '',
    },
    {
        schoolName: 'University of New Mexico',
        athleticsURL: 'https://golobos.com/',
        location: 'Albuquerque, NM',
        logo: 'https://storage.googleapis.com/golobos-com/2020/04/81d2dabd-logo.svg',
        primaryBackground: '',
        primaryText: '',
        safeTextWhite: '',
        safeTextBlack: '',
    },
    {
        schoolName: 'Clemson University ',
        athleticsURL: 'https://clemsontigers.com/',
        location: 'Clemson, SC',
        logo: 'https://clemsontigers.com/wp-content/themes/clemsontigers/assets/images/logo.png',
        primaryBackground: '',
        primaryText: '',
        safeTextWhite: '',
        safeTextBlack: '',
    },

    {
        schoolName: 'University of Virginia',
        athleticsURL: 'https://virginiasports.com/',
        location: 'New Britain, CT',
        logo: 'https://d2o2figo6ddd0g.cloudfront.net/c/e/xrjlk52hvusq3a/logo.png',
        primaryBackground: '',
        primaryText: '',
        safeTextWhite: '',
        safeTextBlack: '',
    },
    {
        schoolName: 'Georgia Institute of Technology',
        athleticsURL: 'https://ramblinwreck.com/',
        location: 'Atlanta, GA',
        logo: 'https://ramblinwreck.com/imgproxy/0BsQEhikL6aCzbQ7EqCWxVhPuOsrd6FZLI2i247wiz0/fit/2500/2500/ce/0/aHR0cHM6Ly9yYW1ibGlud3JlY2suY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDE4LzA2LzEtcHJpbWFyeS1saWdodC1iYWNrZ3JvdW5kLWUxNTQwNDc3NDQ3NjQ4LnBuZw.png',
        primaryBackground: '',
        primaryText: '',
        safeTextWhite: '',
        safeTextBlack: '',
    },
    {
        schoolName: 'Florida State University',
        athleticsURL: 'https://seminoles.com/',
        location: 'Tallahassee, FL',
        logo: 'https://seminoles.com/wp-content/uploads/2017/08/c791c4d6-fsu-logo-8-e1502741638909.png',
        primaryBackground: '',
        primaryText: '',
        safeTextWhite: '',
        safeTextBlack: '',
    },
    {
        schoolName: 'Vanderbilt University',
        athleticsURL: 'https://vucommodores.com/',
        location: 'Nashville, TN',
        logo: 'https://vucommodores.com/wp-content/uploads/2022/03/logo.png',
        primaryBackground: '',
        primaryText: '',
        safeTextWhite: '',
        safeTextBlack: '',
    },
    {
        schoolName: 'The Ohio State University',
        athleticsURL: 'https://ohiostatebuckeyes.com/',
        location: 'Columbus, OH',
        logo: 'https://ohiostatebuckeyes.com/wp-content/uploads/2020/10/new_logo.png',
        primaryBackground: '',
        primaryText: '',
        safeTextWhite: '',
        safeTextBlack: '',
    },
    {
        schoolName: 'University of Kansas',
        athleticsURL: 'https://kuathletics.com/',
        location: 'Lawrence, KS',
        logo: 'https://kuathletics.com/wp-content/uploads/2019/06/Kansas-Athletics-Logo.png',
        primaryBackground: '',
        primaryText: '',
        safeTextWhite: '',
        safeTextBlack: '',
    }
]

function wmt() {
    return schools
}

module.exports = {
    wmt
}