service: collegeSportsCentral
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-west-2
  memorySize: 128
functions:
  app:
    handler: server.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true